
import React from 'react';
import { motion } from 'framer-motion';
import Navbar from '../components/Navbar.tsx';
import Footer from '../components/Footer.tsx';
import { Shield, Lock, Eye, Database, Sparkles } from 'lucide-react';

const Privacy: React.FC = () => {
  return (
    <div className="min-h-screen bg-lightSurface dark:bg-void text-slate-900 dark:text-white transition-colors duration-300 relative overflow-hidden">
      <Navbar />
      
      {/* Background Decor */}
      <div className="absolute top-0 inset-x-0 h-[50vh] bg-gradient-to-b from-teal/5 to-transparent pointer-events-none" />
      <div className="absolute top-1/4 right-0 w-96 h-96 bg-purple-600/5 blur-[120px] rounded-full pointer-events-none" />

      <main className="pt-48 pb-32 px-6 container mx-auto max-w-5xl relative z-10">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="text-center mb-24"
        >
          <span className="text-teal font-black tracking-widest uppercase text-[10px] mb-4 block">SECURITY PROTOCOL V3.1</span>
          <h1 className="text-6xl md:text-8xl font-black font-geist tracking-tighter mb-8 leading-none">
            Data <span className="iridescent-gradient bg-clip-text text-transparent">Sovereignty.</span>
          </h1>
          <p className="text-xl text-slate-500 dark:text-white/40 max-w-2xl mx-auto leading-relaxed font-medium">
            Your data is your intelligence. We build the walls, you hold the keys. Our privacy standards are architected for the era of autonomous agents.
          </p>
        </motion.div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-24">
          {[
            { 
              icon: Lock, 
              title: "End-to-End Encryption", 
              content: "All intelligence data processed by TeamStrength agents is encrypted at rest and in transit using AES-256 and TLS 1.3 standards." 
            },
            { 
              icon: Eye, 
              title: "Zero-Knowledge Storage", 
              content: "We do not sell, rent, or share your raw data. Our agents operate in isolated environments to ensure zero cross-contamination." 
            },
            { 
              icon: Database, 
              title: "Intelligence Isolation", 
              content: "Training datasets are client-specific. Your agents learn only from your data, ensuring your competitive edge remains yours." 
            },
            { 
              icon: Shield, 
              title: "Compliance Ready", 
              content: "TeamStrength is fully compliant with GDPR, CCPA, and SOC2 Type II standards, providing a secure foundation for enterprise growth." 
            }
          ].map((item, i) => (
            <motion.div
              key={i}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ delay: i * 0.1 }}
              viewport={{ once: true }}
              className="p-10 bg-white dark:bg-surface border border-slate-200 dark:border-white/5 rounded-[3rem] shadow-xl dark:shadow-none"
            >
              <div className="w-12 h-12 rounded-2xl bg-teal/10 flex items-center justify-center mb-6 border border-teal/20">
                <item.icon size={20} className="text-teal" />
              </div>
              <h3 className="text-2xl font-black mb-4 font-geist">{item.title}</h3>
              <p className="text-slate-500 dark:text-white/40 font-medium leading-relaxed">{item.content}</p>
            </motion.div>
          ))}
        </div>

        <section className="prose prose-slate dark:prose-invert max-w-none space-y-12">
          <div className="p-12 bg-slate-50 dark:bg-surface/50 border border-slate-200 dark:border-white/5 rounded-[3rem]">
            <h2 className="text-3xl font-black mb-6 font-geist flex items-center gap-3">
              <Sparkles className="text-teal" size={24} /> 1. Information Collection
            </h2>
            <p className="text-slate-500 dark:text-white/40 font-medium text-lg leading-relaxed">
              We collect information that allows our agents to serve your team effectively. This includes account information, usage telemetry, and the content you explicitly provide for processing. We never scrape public data to train global models.
            </p>
          </div>

          <div className="p-12 bg-white dark:bg-surface border border-slate-200 dark:border-white/5 rounded-[3rem]">
            <h2 className="text-3xl font-black mb-6 font-geist">2. Usage Rights</h2>
            <p className="text-slate-500 dark:text-white/40 font-medium text-lg leading-relaxed">
              You retain full ownership of all data inputted and generated by TeamStrength. We act as a processor, operating solely on your instructions and within the bounds of your workspace configurations.
            </p>
          </div>

          <div className="p-12 bg-slate-50 dark:bg-surface/50 border border-slate-200 dark:border-white/5 rounded-[3rem]">
            <h2 className="text-3xl font-black mb-6 font-geist">3. Node Transparency</h2>
            <p className="text-slate-500 dark:text-white/40 font-medium text-lg leading-relaxed">
              Our infrastructure is distributed across secure global nodes. You can select your primary processing node (e.g., PHX-01) to ensure data residency compliance for your specific region.
            </p>
          </div>
        </section>

        <div className="mt-32 p-12 iridescent-gradient rounded-[4rem] text-center shadow-2xl">
          <h2 className="text-4xl font-black text-black mb-6 font-geist tracking-tighter">Have Security Questions?</h2>
          <p className="text-black/70 font-bold mb-10 max-w-xl mx-auto">Our security team is ready to provide full architectural documentation for enterprise vetting.</p>
          <a href="mailto:security@teamstrength.us" className="inline-flex px-10 py-5 bg-black text-white rounded-2xl font-black uppercase text-xs tracking-widest hover:scale-105 transition-transform">
            Contact Security
          </a>
        </div>
      </main>

      <Footer />
    </div>
  );
};

export default Privacy;
