-- TEAMSTRENGTH DEEPSYNC VAULT INITIALIZATION
-- ENFORCING MEANINGFUL HUMAN CONTROL V3.1

-- 1. Teammate Node: The central state of the agentic container
CREATE TABLE public.teammate_node (
    user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    voice_fuel_minutes FLOAT DEFAULT 0.0,
    is_suspended BOOLEAN DEFAULT FALSE,
    channel_config JSONB DEFAULT '{}'::jsonb,
    neural_id TEXT, -- Letta Agent ID
    created_at TIMESTAMPTZ DEFAULT NOW(),
    last_active TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Security Strikes: Immutable audit log for Constitution violations
CREATE TABLE public.security_strikes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    violation_type TEXT NOT NULL, -- e.g., 'illegal_egress', 'constitutional_breach'
    details TEXT,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Skills Catalog: Governance for agentic capabilities
CREATE TABLE public.skills_catalog (
    skill_id TEXT PRIMARY KEY, -- e.g., 'voice_mode'
    tier_required TEXT DEFAULT 'Pro', -- 'Free', 'Pro', 'Enterprise'
    is_active BOOLEAN DEFAULT TRUE
);

-- 4. THE "THREE STRIKES" KILL SWITCH LOGIC
-- Automatically suspends a node if 3 strikes occur within a 24-hour window.
CREATE OR REPLACE FUNCTION public.enforce_three_strikes_policy()
RETURNS TRIGGER AS $$
DECLARE
    strike_count INTEGER;
BEGIN
    -- Count strikes for this user in the last 24 hours
    SELECT COUNT(*) INTO strike_count 
    FROM public.security_strikes 
    WHERE user_id = NEW.user_id 
    AND timestamp > NOW() - INTERVAL '24 hours';

    IF strike_count >= 3 THEN
        UPDATE public.teammate_node 
        SET is_suspended = TRUE 
        WHERE user_id = NEW.user_id;
        
        -- Log the suspension event for audit
        RAISE NOTICE 'User % suspended due to excessive security strikes.', NEW.user_id;
    END IF;
    
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER tr_security_strike_check
AFTER INSERT ON public.security_strikes
FOR EACH ROW EXECUTE FUNCTION public.enforce_three_strikes_policy();

-- RLS POLICIES: Absolute Data Sovereignty
ALTER TABLE public.teammate_node ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.security_strikes ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can only view their own node" ON public.teammate_node
    FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can only view their own strikes" ON public.security_strikes
    FOR SELECT USING (auth.uid() = user_id);